### ISSUE TITLE
[FEATURE] `task-cli register` poderia aceitar um código de atividade para facilitar no scripting

### ISSUE THREAD

**Issue by BarbieroDB1** [rhuangabrielsantos/task-cli#20]
Fiz um código com a intenção de registrar todos os dias de daily, pulando fins-de-semana, porém percebi que o comando `task-cli register` é feito apenas para interação direta

Seria legal se eu pudesse rodar algo do tipo `task-cli register --initial "yyyy-MM-ddThh:mm:ss" --final "yyyy-MM-ddThh:mm:ss" --task-code "1518"`, pois aí poderemos criar scripts que executam isso de forma programática.

Aproveitando, seria legal se as flags `--initial` e `--final` aceitassem ISO Strings pra também facilitar nesse scripting :)

Criei a issue mas quando tiver um tempo livre vou ver de trabalhar nela se ninguém tiver feito; por enquanto vou voltar a lançar horas :D

**Comment by rhuangabrielsantos** [comment]
Achei muito legal a ideia do `--task-code "1518"`. 
Meu único medo sobre o ISO String são as validações, caso consiga trabalhar com os dois formatos e continue funcionando as validações, é super valido essa melhoria.

**Comment by BarbieroDB1** [comment]
usando o pacote [@js-temporal/polyfill](https://github.com/js-temporal/temporal-polyfill), que é o "futuro" dos tratamentos de data/hora no JS(stage 3 no tc39 atualmente), é bem simples de converter datas entre ISO String e um formato custom

Exemplo do meu script:
```ts
function dayToDb1String(day: Temporal.PlainDate, time: Temporal.PlainTime): string {
  const dayString = `${day.day}/${day.month}/${day.year}`;
  const timeString = time.toString();
  return `${dayString} ${timeString}`;
}
```

`Temporal.PlainDate` e `Temporal.PlainTime` são bem fáceis de criar com a função `from`:
```ts
const day = Temporal.PlainDate.from("2022-08-01"); // dia 1 de agosto de 2022
const time = Temporal.PlainTime.from("10:30:01");
console.info(dayToDb1String(day, time));
// >> 1/8/2022 10:30:01
```

pelo meus experimentos, nem precisa fazer padding do zero - "1/8/2022" funciona igual "01/08/2022"

**Comment by rhuangabrielsantos** [comment]
O meu ponto não é nem esse, é o usuário informar os dois formatos de data no mesmo campo, e as validações funcionarem para ambos. Por exemplo:

```
task-cli register --initial="2022-08-01T08:00:00.000Z" --final="2022-08-01T09:00:00.000Z"
```

```
task-cli register --initial="01/08/2022 08:00:00" --final="01/08/2022 09:00:00"
```
Pois atualmente o `cli` faz algumas validações de formato antes de enviar a requisição. Por exemplo, se eu não passo os segundos em algum dos campos, ele manda um erro:

![image](https://user-images.githubusercontent.com/50742592/187925117-4a9d49fa-5773-4810-8ebc-0314d315287a.png)

Resumindo:
Se o sistema entender que ele está enviando um ISO e validar como ISO ou como formato brasileiro e validar como brasileiro, ta tudo certo kkkk

**Comment by rhuangabrielsantos** [comment]
Uma condição importante também que deve-se fazer pra não interferir em um possível script, é quando colocar o campo `--task-code "1518"` ele não perguntar se deseja continuar registrando as horas.
Atualmente quando você registra uma hora com o comando `register` ele pergunta se você deseja continuar registrando:
![image](https://user-images.githubusercontent.com/50742592/188015158-ef17b2b9-fd5a-4d51-9491-998ce9001c38.png)

**Comment by rhuangabrielsantos** [comment]
@BarbieroDB1 criei o PR da adição da flag `task-code`, a parte da data em ISO ainda não alterei pois iria adicionar uma complexidade gigante pra validar as entradas em ambos formatos.

**Comment by rhuangabrielsantos** [comment]
@BarbieroDB1 vou fechar a issue, mas fique à vontade para implementar a data no formato de ISO, mantendo as validações :smile:
